// BinXmlInternal.h Generated by BinTree

#ifndef __BINXMLINTERNAL_H__
#define __BINXMLINTERNAL_H__

// MXM Internal Config File Header
// Use BinTree to convert the internal.xml file into THIS file.
// Automatic settings have been included in the XML to generate the
// Prefix and BaseName, so those fields do not require anything in them.


#ifndef __TOKENSTRUCTS__
#define __TOKENSTRUCTS__


typedef struct _TTokenizedValuePair
{
	int	m_iName;
	int	m_iValue;
} TTokenizedValuePair;

typedef struct _TTokenizedElement
{
	int					m_iName;
	int					m_iValue;
	TTokenizedValuePair	*	m_vplAttributes;
} TTokenizedElement;

typedef struct _TTokenizedNode
{
	int					m_iName;
	TTokenizedValuePair		*	m_vplAttributes;
	TTokenizedElement		*	m_telElements;
	struct _TTokenizedNode	*	m_tnlNodes;
} TTokenizedNode;


#endif // __TOKENSTRUCTS__

const LPCTSTR BTSTR_IntCfg_internal			= _T("internal");
const LPCTSTR BTSTR_IntCfg_automenus			= _T("automenus");
const LPCTSTR BTSTR_IntCfg_menu				= _T("menu");
const LPCTSTR BTSTR_IntCfg_name				= _T("name");
const LPCTSTR BTSTR_IntCfg_submenu			= _T("submenu");
const LPCTSTR BTSTR_IntCfg_title				= _T("title");
const LPCTSTR BTSTR_IntCfg_description		= _T("description");
const LPCTSTR BTSTR_IntCfg_sortfield			= _T("sortfield");
const LPCTSTR BTSTR_IntCfg_item				= _T("item");
const LPCTSTR BTSTR_IntCfg_autodir			= _T("autodir");
const LPCTSTR BTSTR_IntCfg_scripts			= _T("scripts");
const LPCTSTR BTSTR_IntCfg_actionscript		= _T("actionscript");
const LPCTSTR BTSTR_IntCfg_context			= _T("context");
const LPCTSTR BTSTR_IntCfg_mode				= _T("mode");
const LPCTSTR BTSTR_IntCfg_script				= _T("script");
const LPCTSTR BTSTR_IntCfg_xitem				= _T("xitem");
const LPCTSTR BTSTR_IntCfg_skins				= _T("skins");
const LPCTSTR BTSTR_IntCfg_skin				= _T("skin");
const LPCTSTR BTSTR_IntCfg_information		= _T("information");
const LPCTSTR BTSTR_IntCfg_author				= _T("author");
const LPCTSTR BTSTR_IntCfg_copyright			= _T("copyright");
const LPCTSTR BTSTR_IntCfg_skinversion		= _T("skinversion");
const LPCTSTR BTSTR_IntCfg_delays				= _T("delays");
const LPCTSTR BTSTR_IntCfg_load				= _T("load");
const LPCTSTR BTSTR_IntCfg_saver				= _T("saver");
const LPCTSTR BTSTR_IntCfg_messagebox			= _T("messagebox");
const LPCTSTR BTSTR_IntCfg_boxcolor			= _T("boxcolor");
const LPCTSTR BTSTR_IntCfg_bordercolor		= _T("bordercolor");
const LPCTSTR BTSTR_IntCfg_textcolor			= _T("textcolor");
const LPCTSTR BTSTR_IntCfg_shadowcolor		= _T("shadowcolor");
const LPCTSTR BTSTR_IntCfg_systemmenu			= _T("systemmenu");
const LPCTSTR BTSTR_IntCfg_selectcolor		= _T("selectcolor");
const LPCTSTR BTSTR_IntCfg_valuecolor			= _T("valuecolor");
const LPCTSTR BTSTR_IntCfg_selectvaluecolor	= _T("selectvaluecolor");
const LPCTSTR BTSTR_IntCfg_resource			= _T("resource");
const LPCTSTR BTSTR_IntCfg_type				= _T("type");
const LPCTSTR BTSTR_IntCfg_file				= _T("file");
const LPCTSTR BTSTR_IntCfg_entrynamed			= _T("entrynamed");
const LPCTSTR BTSTR_IntCfg_layout				= _T("layout");
const LPCTSTR BTSTR_IntCfg_screen				= _T("screen");
const LPCTSTR BTSTR_IntCfg_layoutelement		= _T("layoutelement");
const LPCTSTR BTSTR_IntCfg_pos				= _T("pos");
const LPCTSTR BTSTR_IntCfg_h					= _T("h");
const LPCTSTR BTSTR_IntCfg_l					= _T("l");
const LPCTSTR BTSTR_IntCfg_t					= _T("t");
const LPCTSTR BTSTR_IntCfg_w					= _T("w");
const LPCTSTR BTSTR_IntCfg_color				= _T("color");
const LPCTSTR BTSTR_IntCfg_constant			= _T("constant");
const LPCTSTR BTSTR_IntCfg_x					= _T("x");
const LPCTSTR BTSTR_IntCfg_y					= _T("y");
const LPCTSTR BTSTR_IntCfg_justify			= _T("justify");
const LPCTSTR BTSTR_IntCfg_source				= _T("source");
const LPCTSTR BTSTR_IntCfg_position			= _T("position");
const LPCTSTR BTSTR_IntCfg_scaling			= _T("scaling");
const LPCTSTR BTSTR_IntCfg_proportional		= _T("proportional");
const LPCTSTR BTSTR_IntCfg_direction			= _T("direction");
const LPCTSTR BTSTR_IntCfg_condition			= _T("condition");
const LPCTSTR BTSTR_IntCfg_multi				= _T("multi");
const LPCTSTR BTSTR_IntCfg_text				= _T("text");
const LPCTSTR BTSTR_IntCfg_scale				= _T("scale");
const LPCTSTR BTSTR_IntCfg_thumbnails			= _T("thumbnails");
const LPCTSTR BTSTR_IntCfg_align				= _T("align");
const LPCTSTR BTSTR_IntCfg_folderimg			= _T("folderimg");
const LPCTSTR BTSTR_IntCfg_passimg			= _T("passimg");
const LPCTSTR BTSTR_IntCfg_selpos				= _T("selpos");
const LPCTSTR BTSTR_IntCfg_numitems			= _T("numitems");
const LPCTSTR BTSTR_IntCfg_minimumheight		= _T("minimumheight");
const LPCTSTR BTSTR_IntCfg_smoothscroll		= _T("smoothscroll");
const LPCTSTR BTSTR_IntCfg_drawsecondary		= _T("drawsecondary");
const LPCTSTR BTSTR_IntCfg_scrollfactor		= _T("scrollfactor");
const LPCTSTR BTSTR_IntCfg_primary			= _T("primary");
const LPCTSTR BTSTR_IntCfg_offsety			= _T("offsety");
const LPCTSTR BTSTR_IntCfg_justifyx			= _T("justifyx");
const LPCTSTR BTSTR_IntCfg_secondary			= _T("secondary");
const LPCTSTR BTSTR_IntCfg_selection			= _T("selection");
const LPCTSTR BTSTR_IntCfg_unselitem			= _T("unselitem");
const LPCTSTR BTSTR_IntCfg_modifier			= _T("modifier");
const LPCTSTR BTSTR_IntCfg_bounds				= _T("bounds");
const LPCTSTR BTSTR_IntCfg_b					= _T("b");
const LPCTSTR BTSTR_IntCfg_r					= _T("r");
const LPCTSTR BTSTR_IntCfg_music				= _T("music");
const LPCTSTR BTSTR_IntCfg_playrandom			= _T("playrandom");
const LPCTSTR BTSTR_IntCfg_playglobal			= _T("playglobal");
const LPCTSTR BTSTR_IntCfg_font				= _T("font");
const LPCTSTR BTSTR_IntCfg_doglow				= _T("doglow");
const LPCTSTR BTSTR_IntCfg_range				= _T("range");
const LPCTSTR BTSTR_IntCfg_infoscreens		= _T("infoscreens");
const LPCTSTR BTSTR_IntCfg_not				= _T("not");

const int BTID_IntCfg_internal			= 0;
const int BTID_IntCfg_automenus			= 1;
const int BTID_IntCfg_menu				= 2;
const int BTID_IntCfg_name				= 3;
const int BTID_IntCfg_submenu			= 4;
const int BTID_IntCfg_title				= 5;
const int BTID_IntCfg_description		= 6;
const int BTID_IntCfg_sortfield			= 7;
const int BTID_IntCfg_item				= 8;
const int BTID_IntCfg_autodir			= 9;
const int BTID_IntCfg_scripts			= 10;
const int BTID_IntCfg_actionscript		= 11;
const int BTID_IntCfg_context			= 12;
const int BTID_IntCfg_mode				= 13;
const int BTID_IntCfg_script				= 14;
const int BTID_IntCfg_xitem				= 15;
const int BTID_IntCfg_skins				= 16;
const int BTID_IntCfg_skin				= 17;
const int BTID_IntCfg_information		= 18;
const int BTID_IntCfg_author				= 19;
const int BTID_IntCfg_copyright			= 20;
const int BTID_IntCfg_skinversion		= 21;
const int BTID_IntCfg_delays				= 22;
const int BTID_IntCfg_load				= 23;
const int BTID_IntCfg_saver				= 24;
const int BTID_IntCfg_messagebox			= 25;
const int BTID_IntCfg_boxcolor			= 26;
const int BTID_IntCfg_bordercolor		= 27;
const int BTID_IntCfg_textcolor			= 28;
const int BTID_IntCfg_shadowcolor		= 29;
const int BTID_IntCfg_systemmenu			= 30;
const int BTID_IntCfg_selectcolor		= 31;
const int BTID_IntCfg_valuecolor			= 32;
const int BTID_IntCfg_selectvaluecolor	= 33;
const int BTID_IntCfg_resource			= 34;
const int BTID_IntCfg_type				= 35;
const int BTID_IntCfg_file				= 36;
const int BTID_IntCfg_entrynamed			= 37;
const int BTID_IntCfg_layout				= 38;
const int BTID_IntCfg_screen				= 39;
const int BTID_IntCfg_layoutelement		= 40;
const int BTID_IntCfg_pos				= 41;
const int BTID_IntCfg_h					= 42;
const int BTID_IntCfg_l					= 43;
const int BTID_IntCfg_t					= 44;
const int BTID_IntCfg_w					= 45;
const int BTID_IntCfg_color				= 46;
const int BTID_IntCfg_constant			= 47;
const int BTID_IntCfg_x					= 48;
const int BTID_IntCfg_y					= 49;
const int BTID_IntCfg_justify			= 50;
const int BTID_IntCfg_source				= 51;
const int BTID_IntCfg_position			= 52;
const int BTID_IntCfg_scaling			= 53;
const int BTID_IntCfg_proportional		= 54;
const int BTID_IntCfg_direction			= 55;
const int BTID_IntCfg_condition			= 56;
const int BTID_IntCfg_multi				= 57;
const int BTID_IntCfg_text				= 58;
const int BTID_IntCfg_scale				= 59;
const int BTID_IntCfg_thumbnails			= 60;
const int BTID_IntCfg_align				= 61;
const int BTID_IntCfg_folderimg			= 62;
const int BTID_IntCfg_passimg			= 63;
const int BTID_IntCfg_selpos				= 64;
const int BTID_IntCfg_numitems			= 65;
const int BTID_IntCfg_minimumheight		= 66;
const int BTID_IntCfg_smoothscroll		= 67;
const int BTID_IntCfg_drawsecondary		= 68;
const int BTID_IntCfg_scrollfactor		= 69;
const int BTID_IntCfg_primary			= 70;
const int BTID_IntCfg_offsety			= 71;
const int BTID_IntCfg_justifyx			= 72;
const int BTID_IntCfg_secondary			= 73;
const int BTID_IntCfg_selection			= 74;
const int BTID_IntCfg_unselitem			= 75;
const int BTID_IntCfg_modifier			= 76;
const int BTID_IntCfg_bounds				= 77;
const int BTID_IntCfg_b					= 78;
const int BTID_IntCfg_r					= 79;
const int BTID_IntCfg_music				= 80;
const int BTID_IntCfg_playrandom			= 81;
const int BTID_IntCfg_playglobal			= 82;
const int BTID_IntCfg_font				= 83;
const int BTID_IntCfg_doglow				= 84;
const int BTID_IntCfg_range				= 85;
const int BTID_IntCfg_infoscreens		= 86;
const int BTID_IntCfg_not				= 87;

extern LPCTSTR g_szBtTknsInternal[];

extern int g_iBtTreeInternal[];

#endif // __BINXMLINTERNAL_H__
