// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 4UL

#define resource_MatteBlack_OFFSET 0UL
#define resource_ShinyBlack_OFFSET 20UL
#define resource_Cord_OFFSET 40UL
#define resource_CursorArrow_OFFSET 60UL
